[workspace]
resolver = "2"
members = [
  "bm1366",
  "bm1370",
  "bm1397",
  "bm13xx-asic",
  "bm13xx-chain",
  "bm13xx-protocol",
]

[workspace.dependencies]
crc = "3.3"
defmt = { version = "1.0" }
derive_more = { version = "2.0", default-features = false }
embedded-hal = "1.0"
embedded-hal-async = "1.0"
embedded-io-async = "0.6"
fugit = "0.3"
heapless = "0.9"
log = "0.4"
rustversion = "1.0"
